config/routes.rb
Rails.application.routes.draw do
  get 'questions/show'

  root 'static_pages#home'
  get '/about', to: 'static_pages#about'

  get '/questions/all', to: 'questions#all'
  get '/questions/new', to: 'questions#new'
  post '/questions', to: 'questions#create'
  get '/questions/:id', to: 'questions#show'
  get '/questions/:id/edit', to: 'questions#edit', as: 'choose'
  get '/questions/:id/approve', to: 'questions#approve'
  get '/random', to: 'questions#random'
  delete '/questions/:id/delete', to: 'questions#delete', as: 'delete'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, presence: true, length: {maximum: 80}
  validates :choice_a, presence: true, length: {maximum: 8}
  validates :choice_b, presence: true, length: {maximum: 8}
  validates :choice_c, presence: true, length: {maximum: 8}
  validates :choice_d, presence: true, length: {maximum: 8}
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum: 50}, uniqueness: true
  has_secure_password
  validates :password, presence: true, length: {minimum: 8, maximum: 250}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                              BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :admin_check, only: [:approve, :all, :delete]

  def new
    @question = Question.new
  end

  def approve
    @question = Question.find(params[:id])
    @question.approved = true
    @question.save
    flash[:success] = "Question approved."
    redirect_to '/questions/all'
  end

  def create
    @question = Question.new(question_params)
    @question.approved = false
    if @question.save
      flash[:success] = "Question created! It should be approved in a little bit."
      redirect_to '/'
    else
      flash[:danger] = "Question wasn't created. Try fixing the errors."
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @choices = [@question.choice_a, @question.choice_b, @question.choice_c, @question.choice_d]
    @counts = [@question.count_a, @question.count_b, @question.count_c, @question.count_d]
    render :layout => 'question_layout'
  end

  def all
    @questions = Question.all.order(created_at: :desc)
  end

  def delete
    @question = Question.find(params[:id]).destroy
    flash[:success] = "Question deleted."
    redirect_to '/questions/all'
  end

  def edit
    @question = Question.find(params[:id])
    case params[:choice]
    when 'a'
      @question.count_a += 1
    when 'b'
      @question.count_b += 1
    when 'c'
      @question.count_c += 1
    when 'd'
      @question.count_d += 1
    end
    @question.save

    puts "count of question #{params[:id]}"
    puts [@question.count_a, @question.count_b, @question.count_c, @question.count_d]
    redirect_to random_path
  end

  def random
    # cookies.delete :visited_questions
    avail_questions = Question.where(approved: true).pluck(:id)

    rand_question = avail_questions[rand(avail_questions.length)]
    if !(cookies[:visited_questions].nil?) && cookies[:visited_questions].split("-").length < avail_questions.length
      visited_questions = cookies[:visited_questions].split("-")

      while visited_questions.include? rand_question.to_s
        rand_question = avail_questions[rand(avail_questions.length)]
      end

      visited_questions.push(rand_question)

      cookies[:visited_questions] = {
        value: visited_questions.join("-"),
        expires: 1.day.from_now }

    else
      cookies[:visited_questions] = rand_question.to_s
    end
    puts "redirecting to #{rand_question}"
    redirect_to "/questions/#{rand_question}"
  end

  private

    def question_params
      params.require(:question).permit(:question, :choice_a, :choice_b, :choice_c, :choice_d)
    end

    def admin_check
      unless logged_in
        flash[:danger] = "You'll need to log in to access this page."
        redirect_to login_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(name: params[:session][:name])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_url
      flash[:success] = "Welcome to admin mode!"
    else
      flash.now[:danger] = "Invalid username or password."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in
    flash[:success] = "Successfully logged out."
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_logo.html.erb
<span class="logo">honestly<strong>y</strong></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:header) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  </head>

  <body>
    <div class="header">
      <h1><%= yield(:header) %></h1>
      <div class="header-links <%= "header-admin" if logged_in %>">
        <%= link_to "home", root_path %>
        <%= link_to "submit a question", questions_new_path %>
        <%= link_to "just play already", random_path %>
        <% if logged_in %>
          <%= link_to "all questions", questions_all_path %>
          <%= link_to "log out", logout_path, method: :delete %>
        <% end %>
      </div>
    </div>
    <% flash.each do |message_type, message| %>
      <div class="flash <%= message_type %>"><%= message %></div>
    <% end %>
    <div id="content-outer" class="hidden">
      <%= yield %>
    </div>
    <div id="footer">
      <%= link_to "home", root_path %>
      <%= link_to "faq", about_path %>
      <%= link_to "just play already", random_path %>
    </div>
    <script>
    var hideTimeout, redirectTimeout;
    $(document).ready(function() {
      $("*").removeClass("footer-show");
      clearTimeout(hideTimeout);
      clearTimeout(redirectTimeout);
      $("#timer").stop();
      $("#content-outer").removeClass("hidden");
    });
    </script>
  </body>
</html>

app/views/layouts/question_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= favicon_link_tag "favicon.ico" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  </head>

  <body>
    <div id="content-outer" class="question-content hidden">
      <%= yield %>
    </div>
    <div id="footer" style="margin-top: 0">
      <%= link_to "home", root_path %>
      <%= link_to "faq", about_path %>
    </div>
  </body>
</html>

app/views/questions/all.html.erb
<% provide :header, "all questions" %>
<ol id="all-questions">
  <% @questions.each do |question| %>
    <li>
      <h4>Question #<%= question.id %></h4>
      <h2><%= question.question %></h2>
      <p><%= question.choice_a %> - <span class="vote-amt"><%= question.count_a %> votes</span></p>
      <p><%= question.choice_b %> - <span class="vote-amt"><%= question.count_b %> votes</span></p>
      <p><%= question.choice_c %> - <span class="vote-amt"><%= question.count_c %> votes</span></p>
      <p><%= question.choice_d %> - <span class="vote-amt"><%= question.count_d %> votes</span></p>
      <%= link_to "go to", "/questions/#{question.id}" %>
      <%= link_to "delete", "/questions/#{question.id}/delete", method: :delete, data: {confirm: "Are you sure?"} %>
      <% unless question.approved? %>
        <%= link_to "approve", "/questions/#{question.id}/approve" %>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/questions/new.html.erb
<% provide :header, "new question" %>

<div class="form-outer">
  <%= form_for @question do |f| %>
    <%= render 'shared/error_messages' %>
    
    <%= f.label :question, "Question" %>
    <%= f.text_field :question, maxlength: 80, style: "width: 100%" %>

    <%= f.label :choice_a, "Choice A" %>
    <%= f.text_field :choice_a, maxlength: 8 %>

    <%= f.label :choice_b, "Choice B" %>
    <%= f.text_field :choice_b, maxlength: 8 %>

    <%= f.label :choice_c, "Choice C" %>
    <%= f.text_field :choice_c, maxlength: 8 %>

    <%= f.label :choice_d, "Choice D" %>
    <%= f.text_field :choice_d, maxlength: 8 %>

    <%= f.submit "create", class: "fancy-button" %>
  <% end %>
</div>

app/views/questions/show.html.erb
<% provide :title, "honestlyy" %>

<h2 class="question"><%= @question.question %></h2>
<div id="timer" class="start"></div>
<div id="choices-outer">
  <div id="bar-background">
    <% @counts.each_with_index do |count, index| %>
      <div id="bar-<%= index %>" class="bar inactive" style="height: 0; transition-delay: <%= index*0.1 %>s">
        <p><%= count %></p>
      </div>
    <% end %>
  </div>
  <% @choices.each_with_index do |choice, index| %>
    <%= link_to choice, 'javascript:;',
        id: "choice-#{index}",
        class: "choice inactive",
        style: "margin-bottom: 0; transition: transform 0.25s, color 0.25s, margin-bottom 0.25s #{index*0.1}s;",
        href: choose_path(id: @question.id, choice: ("a"..."z").to_a[index]) %>
  <% end %>
</div>
<p id="scroll-down">&#x2303;</p>

<script>
var hideTimeout, redirectTimeout;
var counts = <%= @counts %>;
counts[0]--;
var total = counts.reduce(function(a, b) { return a + b; }, 0);
var heights = [0, 0, 0, 0];
var questionHeight = 70;
var updateHeights = function(choice) {
  total++;
  console.log(counts);
  counts[choice]++;
  console.log(counts);
  $("#bar-"+choice+" > p").html(counts[choice]);
  for(i = 0; i < counts.length; i++) {
    heights[i] = (counts[i]/total)*100;
    console.log(heights);
    biggestHeight = window.innerHeight - (questionHeight + 100)
    $("#choice-"+i).css("margin-bottom",  biggestHeight*(heights[i]/120)+90+"px");
    $("#bar-"+i).css("height", biggestHeight*(heights[i]/120)+90+"px");
  }
}

var finish = function() {
  $("#footer, #choices-outer, #scroll-down").removeClass("footer-show");
  $(".choice, #scroll-down").addClass("disabled");
  $(".bar, .choice").removeClass("inactive");
  var that = this;
  hideTimeout = setTimeout(function() {
    $("#content-outer").addClass("hidden");
  }, 2000);
  redirectTimeout = setTimeout(function() {
    window.location = "/random";
  }, 2500);
}

var windowResize = function() {
  questionHeight = $(".question").height();
  $("#timer").css("top", questionHeight + 20 + "px");
}

$(document).ready(function() {
  $(window).resize(function() {
    windowResize();
  });
  windowResize();
  $("#timer").stop();
  $("#content-outer").removeClass("hidden");
  $("#content-outer.question-content").ready(function() {
    $("#timer").animate({
      width: "100vw"
    }, 5000, 'linear', function() {finish();});
  });

  updateHeights(0);

  $("#scroll-down").click(function() {
    $("#footer, #choices-outer, #scroll-down").toggleClass("footer-show")
  });

  $("a").click(function() {
    $("*").removeClass("footer-show");
    clearTimeout(hideTimeout);
    clearTimeout(redirectTimeout);
    $("#timer").stop();
  });

  $(".choice").click(function(event) {
    $("#timer").stop();
    event.preventDefault();
    var choice = $(this).attr("id").substr(7);
    updateHeights(choice);
    $(this).addClass("selected");
    $(".choice, #scroll-down").addClass("disabled");
    $(".bar, .choice").removeClass("inactive");
    var that = this;
    hideTimeout = setTimeout(function() {
      $("#content-outer").addClass("hidden");
    }, 2000);
    redirectTimeout = setTimeout(function() {
      window.location = $(that).attr("href");
    }, 2500);
  });
});
</script>

app/views/shared/_error_messages.html.erb
<% if @question.errors.any? %>
  <div id="errors-outer">
    <h4>Your question has <%= pluralize(@question.errors.count, "error") %>.</h4>
    <ul>
      <% @question.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide :header, "FAQ" %>
<h2>How do I play?</h2>
<p>All you really have to do is answer some meaningless questions based on your instincts.</p>
<p>Don't think too hard for one question; they're timed. Well they will be eventually...</p>
<h2>Why?</h2>
<p>Why not?</p>
<h2>This game is stupid.</h2>
<p>That's not a question. And it's actually fun.</p>
<h2>Is this thing on GitHub?</h2>
<p><%= link_to "Yeah, looks like it.", "https://github.com/noahfiner/honestlyy" %> It's probably easy to hack tbh.</p>

app/views/static_pages/home.html.erb
<% provide :header, "home" %>
<h3><%= render 'layouts/logo' %></h3>
<p style="font-size: 30px; text-align: center; margin-bottom: 100px"><%= link_to "Click here to play.", random_path %></p>
<h2>Do you have any questions?</h2>
<p>You should probably visit the incredibly helpful <%= link_to "FAQ", about_path %></p>